docs/4_4_1_can.adoc
docs/4____network_abstraction.adoc

Resolve issues #19 and #20

---

docs/4_4_1_can.adoc

Fixed issue "structural parameters with '-' violate structural naming convention"

Fixed issue 22

---

docs/1____introduction.adoc
docs/4____network_abstraction.adoc
docs/6____known_limitations_of_this_standard.adoc
docs/examples/fmi_ls_bus_manifest_example.xml
docs/schema/fmi3LayeredStandardBusManifest.xsd

Fixed issue "Layered Standard Manifest File is missing for fmi-ls-bus"

Fixed issue 24

---

docs/4_4_1_can.adoc
docs/4____network_abstraction.adoc

Fixed issue: "Remove NOOP Operation"

Fixed issue 25

---

docs/2____common_concepts.adoc
docs/4____network_abstraction.adoc

48 formal correction of fmi3 specification and fmi3true

---

docs/2____common_concepts.adoc
docs/3____physical_signal_abstraction.adoc
docs/4____network_abstraction.adoc

Fixed issue 58

---

docs/2____common_concepts.adoc
docs/3____physical_signal_abstraction.adoc
docs/4_4_1_can.adoc
docs/4____network_abstraction.adoc

Fixed issue 56

---

docs/headers/fmi3LsBus.h
docs/headers/fmi3LsBusCan.h

79 fix fmi ls bus bugs within headers

---

docs/3____physical_signal_abstraction.adoc
docs/4____network_abstraction.adoc
docs/examples/X_network4FMI_terminalsAndIcons_highCut.xml
docs/examples/X_network4FMI_terminalsAndIcons_lowCut.xml

Fixes issue #81 (see issue for details).

Fixed issue 81

---

docs/4_4_1_can.adoc

Fixed issue 100

---

docs/3____physical_signal_abstraction.adoc

@andreas-junghanns is this solution OK for you? Thanks!

Fixed issue #85

---

README.md
docs/4____network_abstraction.adoc

Fixing issue #75

---

docs/2____common_concepts.adoc
headers/fmi3LsBusUtil.h
headers/fmi3LsBusUtilCan.h

Moved Util headers and add description chapter

---

docs/index.adoc

No tags yet, just for preparation

Fix name of LS and add revision info

---

docs/4_4_1_can.adoc
docs/4_4_2_lin.adoc
docs/4____network_abstraction.adoc
headers/fmi3LsBus.h
headers/fmi3LsBusCan.h
headers/fmi3LsBusUtil.h
headers/fmi3LsBusUtilCan.h

Synchronize Operation Argument names and names in headers, add Format Error API

---

docs/4_4_1_can.adoc

Refinement of the CAN ID description

---

docs/1____introduction.adoc

Add rational for isBusSimulation attribute within manifest file

---

docs/2____common_concepts.adoc

IMHO it doesn't make sense to talk about mandatory/optional in this context

Remove optional/mandatory from provided c-api section

---

LICENSE.txt
README.md
docs/0____preamble.adoc
docs/5____additional_content.adoc

@chrbertsch analogous change as in fmi-ls-xcp.

Fix copyright notices and license url

---

docs/3____physical_signal_abstraction.adoc

Only recommend high-cut variable names

---

.github/workflows/build-ls-bus.yml

A new version of actions/upload-artifact requires adaptions of the build pipeline

Fixed build pipeline

---

docs/3____physical_signal_abstraction.adoc
docs/4____network_abstraction.adoc
docs/examples/X_network4FMI_terminalsAndIcons_highCut_autosar.xml
docs/examples/X_network4FMI_terminalsAndIcons_highCut_dbc.xml

This should (partly) clarify #199

Improve high cut clocks section
